### ISSUE TITLE
Write code to output as CTF file

### ISSUE THREAD

**Issue by merrygoat** [LightForm-group/beta-reconstruction#3]
At the beginning can write out an CTF file as this should be a relatively simple format.

**Comment by mikesmic** [comment]
EBSD map objects can now be created from runtime data in defdap MechMicroMan/DefDAP@336b6482dc348dca141c885e11b6f6336e7ccf04 and map objects can be saved to a CTF file MechMicroMan/DefDAP@23f52a1504c040f60d235a8c8c3bcbecfd401111

Waiting on #9 now
