### ISSUE TITLE
Load in data with different number of data values per point

### ISSUE THREAD

**Issue by christopher-daniel** [LightForm-group/beta-reconstruction#7]
Loading in test data (ZrNb_hot_rolled_alpha) leads to a value error, since there are fewer data values per point than expected in the array. This may be due to converting or saving the file in Aztec Channel 5. Quick fix is to comment out line 95 in file_readers.py in defdap ('IB6', 'f').

**Comment by mikesmic** [comment]
This has been fixed in a feature branch of defdap for loading in multiphase EBSD maps. I'll update when the fix makes it into the current develop version

**Comment by mikesmic** [comment]
Fixed in release 0.93 of defdap
