### ISSUE TITLE
Tidy example notebooks

### ISSUE THREAD

**Issue by merrygoat** [LightForm-group/beta-reconstruction#8]
We need a single notebook which has a clear narrative and demonstration of the current features.

It also needs an example data set to use for the notebooks. This can probably be done easily using the ZrNb_triplepoint dataset as this is only 4 Mb, I think small enough to include in the git repo.

**Comment by merrygoat** [comment]
@mikesmic Could you please review my notebook in the notebook_tidying branch. I have tried my best to understand what is going on but it may not be all the way there. I have left a couple of notes in red that particularly need attention.

**Comment by mikesmic** [comment]
Example notebook looks good. Runs over the basic reconstruction process and exploring the reconstruction data.
